# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ddc3528e1f6d9da594c6b7fb8cba4d524097760da07a8ee3da0158c36a0dfff9ffce68f028ed80d608345454d0bae4f7b82ce74ab5772840cae0c1d0d43c4b6

test:
  secret_key_base: fca031e918e419ce2e4284b9330cfc777f520d7b9ae5db8bcd535f0940530402ad4fc430b98358e32ddfd771f615a1cc4d0ff0da56c5a48f25fc4148baa30327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
